services:
  server:
    build: ./server
    working_dir: /app
    command:
      [
        "sh",
        "-c",
        "iptables -w -t mangle -C PREROUTING -i eth0 -p tcp -m tcp -d 172.31.0.60 --dport 8080 -j TEE --gateway 172.31.0.59 2>/dev/null || \
         iptables -w -t mangle -A PREROUTING -i eth0 -p tcp -m tcp -d 172.31.0.60 --dport 8080 -j TEE --gateway 172.31.0.59; \
         iptables -w -t mangle -C OUTPUT -o eth0 -p tcp -m tcp -s 172.31.0.60 --sport 8080 -j TEE --gateway 172.31.0.59 2>/dev/null || \
         iptables -w -t mangle -A OUTPUT -o eth0 -p tcp -m tcp -s 172.31.0.60 --sport 8080 -j TEE --gateway 172.31.0.59; \
         exec python3 server.py --host 0.0.0.0 --port 8080 --verbose"
      ]
    cap_add:
      - NET_ADMIN
    networks:
      lan:
        ipv4_address: 172.31.0.60
  normal:
    build: ./normal
    working_dir: /app
    command: ["python3", "normal_client.py", "172.31.0.60", "8080", "--verbose"]
    networks:
      lan:
        ipv4_address: 172.31.0.57
  bot:
    build: ./bot
    working_dir: /app
    command:
      [
        "./bot",
        "172.31.0.60",
        "8080",
        "-attack", "SQLI",
        "-seed", "10",
        "-verbose"
      ]
    networks:
      lan:
        ipv4_address: 172.31.0.58
  ips:
    build: ./ips
    working_dir: /app
    command:
      [
        "./main",
        "-mode=sniffing",
        "-iface=eth0",
        "-bpf=tcp and host 172.31.0.60 and port 8080"
      ]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      lan:
        ipv4_address: 172.31.0.59
networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
