services:
  server:
    build: ./server
    working_dir: /app
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    volumes:
      - ./runtime-logs/server:/logs
    environment:
      TZ: Asia/Seoul
      SERVER_IP: ${SERVER_CONTAINER_IP:-172.31.0.60}
      SERVER_PORT: ${SERVER_PORT:-8080}
      SERVER_GATEWAY: ${IPS_CONTAINER_IP:-172.31.0.59}
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      lan:
        ipv4_address: ${SERVER_CONTAINER_IP:-172.31.0.60}
  normal:
    build: ./normal
    working_dir: /app
    command: ["sh", "/app/run.sh"]
    environment:
      TZ: Asia/Seoul
      SERVER_IP: ${SERVER_CONTAINER_IP:-172.31.0.60}
      SERVER_PORT: ${SERVER_PORT:-8080}
      CLIENT_VERBOSE: 1
    networks:
      lan:
        ipv4_address: ${NORMAL_CONTAINER_IP:-172.31.0.57}
  bot:
    build: ./bot
    working_dir: /app
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    volumes:
      - ./runtime-logs/bot:/logs
    environment:
      TZ: Asia/Seoul
      BOT_IP: ${SERVER_CONTAINER_IP:-172.31.0.60}
      BOT_PORT: ${SERVER_PORT:-8080}
      BOT_MODE: ${BOT_MODE:-url}
      BOT_PAYLOAD: ${BOT_PAYLOAD:-sqli}
      BOT_URI_SIZE: ${BOT_URI_SIZE:-8192}
      BOT_BODY_SIZE: ${BOT_BODY_SIZE:-1048576}
      BOT_HEADER_SIZE: ${BOT_HEADER_SIZE:-4096}
      BOT_PREFIX: ${BOT_PREFIX:-}
      BOT_SUFFIX: ${BOT_SUFFIX:-}
      BOT_SEED: ${BOT_SEED:-10}
      BOT_VERBOSE: ${BOT_VERBOSE:-1}
      BOT_COUNT: ${BOT_COUNT:-20}
    stdin_open: true
    tty: true
    networks:
      lan:
        ipv4_address: ${BOT_CONTAINER_IP:-172.31.0.58}
  ips:
    build: ./ips
    working_dir: /app
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    volumes:
      - ./runtime-logs/ips:/logs
      - ./ips/DB:/app/DB
    ports:
      - "8090:8090"
    environment:
      TZ: Asia/Seoul
      IPS_REGEX_ENGINE: ${IPS_REGEX_ENGINE:-hs}
      IFACE: ${IPS_IFACE:-eth0}
      BPF: tcp and host ${SERVER_CONTAINER_IP:-172.31.0.60} and port ${SERVER_PORT:-8080}
      MODE: ${IPS_MODE:-sniffing}
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      lan:
        ipv4_address: ${IPS_CONTAINER_IP:-172.31.0.59}
networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: ${LAN_SUBNET:-172.31.0.0/24}
