worker_processes  1;

pid /home/doogunwo/training/Mini-IPS/server/nginx-netns.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /dev/stdout;
    error_log  /dev/stderr info;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name _;

        root /home/doogunwo/training/Mini-IPS/server;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
